export const url_path = 'http://xn--299as6voca478bs7ip4ijkdpxj.kr'


export const src_info_list = [
    // { src_type:'png', img_path:'img', img_name:'Page1'},
    // { src_type:'png', img_path:'img', img_name:'Page1-2'},
    // { src_type:'png', img_path:'img', img_name:'Page1-3'},
    { src_type:'png', img_path:'img', img_name:'Page2'},
    { src_type:'png', img_path:'img', img_name:'Page2-2'},
    { src_type:'png', img_path:'img', img_name:'Page2-3'},
    { src_type:'png', img_path:'img', img_name:'Page3'},
    { src_type:'png', img_path:'img', img_name:'Page3-2'},
    { src_type:'png', img_path:'img', img_name:'Page4'},
    { src_type:'png', img_path:'img', img_name:'Page5-01'},
    { src_type:'png', img_path:'img', img_name:'Page5-02'},
    { src_type:'gif', img_path:'gif', img_name:'Page5-02-1'},
    { src_type:'png', img_path:'img', img_name:'Page5-03'},
    { src_type:'gif', img_path:'gif', img_name:'Page5-03-1'},
    { src_type:'gif', img_path:'gif', img_name:'Page5-03-2'},
    { src_type:'png', img_path:'img', img_name:'Page5-04'},
    { src_type:'gif', img_path:'gif', img_name:'Page5-04-1'},
    { src_type:'png', img_path:'img', img_name:'Page5-05'},
    { src_type:'gif', img_path:'gif', img_name:'Page5-05-1'},
    { src_type:'gif', img_path:'gif', img_name:'Page5-05-2'},
    { src_type:'gif', img_path:'gif', img_name:'Page5-05-3'},
    { src_type:'png', img_path:'img', img_name:'Page5-06'},
    { src_type:'gif', img_path:'gif', img_name:'Page5-06-1'},
    { src_type:'gif', img_path:'gif', img_name:'Page5-06-2'},
    { src_type:'png', img_path:'img', img_name:'Page5-07'},
    { src_type:'gif', img_path:'gif', img_name:'Page5-07-1'},
    { src_type:'png', img_path:'img', img_name:'Page5-08'},
    { src_type:'gif', img_path:'gif', img_name:'Page5-08-1'},
    { src_type:'png', img_path:'img', img_name:'Page5-09'},
    { src_type:'gif', img_path:'gif', img_name:'Page5-09-1'},
    { src_type:'png', img_path:'img', img_name:'Page5-10'},
    { src_type:'gif', img_path:'gif', img_name:'Page5-10-1'},
    { src_type:'png', img_path:'img', img_name:'Page5-11'},
    { src_type:'gif', img_path:'gif', img_name:'Page5-11-1'},
    { src_type:'png', img_path:'img', img_name:'Page6'},
    { src_type:'png', img_path:'img', img_name:'Page6-2'}
]